Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.















class Solution {
public:
    char findTheDifference(string s, string t) {
        int m=s.length();
        int n=t.length();
        int freq[26];
        fill(freq, freq+26, 0);
        for(int i=0;i<n;i++){
            freq[t[i]-'a']++;
        }
        for(int i=0;i<m;i++){
            freq[s[i]-'a']--;
        }
        int i;
        for(i=0;i<26;i++){
            if(freq[i]!=0) break;
        }
        return 'a'+i;
    }
};


// Bit manipulation
class Solution {
public:
    char findTheDifference(string s, string t) {
        int m=s.length();
        int n=t.length();
        if(m==0) return t[0];
        char res=s[0];
        for(int i=1;i<m;i++)
            res^=s[i];
        for(int i=0;i<n;i++)
            res^=t[i];
        return char(res);
    }
};
